# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Comment

# Model Form Field configuration
form: ~/plugins/winter/test/models/comment/fields_simple.yaml

# Model Class name
modelClass: Winter\Test\Models\Comment

# Default redirect location
defaultRedirect: winter/test/posts

# Create page
create:
    title: Create Comments
    redirect: winter/test/posts/update/:id
    redirectClose: winter/test/posts

# Update page
update:
    title: Edit Comments
    redirect: winter/test/posts
    redirectClose: winter/test/posts

# Preview page
preview:
    title: Preview Comments
